version: '3'
services:
  redis:
    container_name: redis
    ports:
      - '${REDIS_BIND_PORT}:${REDIS_MAP_PORT}'
    image: redis:alpine

  csdgan:
    container_name: ${APP_NAME}
    ports:
      - '${APP_BIND_PORT}:${APP_MAP_PORT}'
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=redis://redis-server:${REDIS_MAP_PORT}/0
      - DB_PW=${DB_PW}
      - DB_HOST=${DB_NAME}
    links:
      - redis:redis-server
      - mysql:dbserver
    volumes:
      - MyDataVolume:/MyDataVolume
    image: atrus619/${APP_NAME}:latest
    depends_on:
      - redis
      - ${DB_NAME}

  rq-worker:
    container_name: rq-worker
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=redis://redis-server:${REDIS_MAP_PORT}/0
      - DB_PW=${DB_PW}
      - DB_HOST=${DB_NAME}
    links:
      - redis:redis-server
      - ${DB_NAME}:dbserver
    volumes:
      - MyDataVolume:/MyDataVolume
    entrypoint:
      - venv/bin/rq
    image: atrus619/${APP_NAME}:latest
    depends_on:
      - redis
      - ${DB_NAME}
    command: worker -u redis://redis-server:${REDIS_MAP_PORT}/0 CSDGAN

  mysql:
    container_name: ${DB_NAME}
    hostname: ${DB_NAME}
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${APP_NAME}
      - MYSQL_USER=${APP_NAME}
      - MYSQL_PASSWORD=${DB_PW}
    image: mysql/mysql-server:5.7

volumes:
  MyDataVolume: