version: '2.3'

services:
  redis:
    container_name: redis
    ports:
      - '${REDIS_BIND_PORT}:${REDIS_MAP_PORT}'
    image: redis:alpine

  csdgan:
    container_name: ${APP_NAME}
    ports:
      - '${APP_BIND_PORT}:${APP_MAP_PORT}'
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=redis://redis-server:${REDIS_MAP_PORT}/0
      - DB_USER=${DB_USER}
      - DB_PW=${DB_PW}
      - DB_HOST=${DB_NAME}
      - APP_NAME=${APP_NAME}
      - DOCKERIZED=1
    links:
      - redis:redis-server
      - mysql:dbserver
    volumes:
      - MyDataVolume:/MyDataVolume
    command: '${RELOAD}'
    image: ${APP_NAME}:latest #atrus619/${APP_NAME}:latest
    depends_on:
      - redis
      - mysql
    runtime: nvidia

  rq-worker:
    container_name: rq-worker
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=redis://redis-server:${REDIS_MAP_PORT}/0
      - DB_USER=${DB_USER}
      - DB_PW=${DB_PW}
      - DB_HOST=${DB_NAME}
      - APP_NAME=${APP_NAME}
      - DOCKERIZED=1
    links:
      - redis:redis-server
      - mysql:dbserver
    volumes:
      - MyDataVolume:/MyDataVolume
    entrypoint:
      - venv/bin/rq
    image: ${APP_NAME}:latest #atrus619/${APP_NAME}:latest
    depends_on:
      - redis
      - mysql
    command: worker -u redis://redis-server:${REDIS_MAP_PORT}/0 CSDGAN
    runtime: nvidia

  mysql:
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${APP_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PW}
    image: mysql/mysql-server:5.7

volumes:
  MyDataVolume: