DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS run;
DROP TABLE IF EXISTS status;
DROP TABLE IF EXISTS status_info;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  last_login TIMESTAMP NOT NULL,
  num_logins INTEGER NOT NULL
);

CREATE TABLE run (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  end_time TIMESTAMP NOT NULL,
  type TEXT NOT NULL,
  filesize INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE status (
  run_id INTEGER NOT NULL,
  line_nbr INTEGER NOT NULL,
  status_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (run_id, line_nbr),
  FOREIGN KEY (status_id) REFERENCES status_info (id)
  FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE status_info (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  descr TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);